<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Missing extends Model
{
    use HasFactory;

    protected $table = 'missings';

    // Define the fillable attributes
    protected $fillable = [
        'name',
        'description',
        'missing_since',
        'location',
        'contact_number',
        'image',
        'user_id',
    ];

    // Define the relationship with the User model
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model){
            if (empty($model->user_id)){
                $model->user_id = \Auth::user()->id;
            }
        });
    }
}
